apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simulator-first-responder-demo-wvpf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simulator-first-responder-demo-wvpf
    app.kubernetes.io/part-of: firstresponder-demo
  name: simulator-first-responder-demo-wvpf
  namespace: rhn-sa-sshaaf-tenant
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: simulator-first-responder-demo-wvpf
    weight: null
status: {}
