apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simulator-first-responder-demo-wvpf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simulator-first-responder-demo-wvpf
    app.kubernetes.io/part-of: firstresponder-demo
  name: simulator-first-responder-demo-wvpf
  namespace: rhn-sa-sshaaf-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: simulator-first-responder-demo-wvpf
status:
  loadBalancer: {}
