apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-guoq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-guoq
    app.kubernetes.io/part-of: firstresponder-demo
  name: devfile-sample-guoq
  namespace: rhn-sa-sshaaf-tenant
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: devfile-sample-guoq
    weight: null
status: {}
