apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backend-first-responder-demo-q5de
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-first-responder-demo-q5de
    app.kubernetes.io/part-of: firstresponder-demo
  name: backend-first-responder-demo-q5de
  namespace: rhn-sa-sshaaf-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: backend-first-responder-demo-q5de
status:
  loadBalancer: {}
